// THIS FILE IS GENERATED BY CODE GENERATOR. DO NOT CHANGE MANUALLY.
/* tslint:disable */
/* eslint-disable */

interface Validator {
  response: (data: any) => boolean
  requestBody: (data: any) => boolean
  parameters: (data: any) => boolean
}

export const GetPetsOperationValidator: Validator

export const CreatePetOperationValidator: Validator

export const GetPetOperationValidator: Validator
