// THIS FILE IS GENERATED BY CODE GENERATOR. DO NOT CHANGE MANUALLY.
/* tslint:disable */
/* eslint-disable */

interface Validator {
  response: (data: any) => boolean
  requestBody: (data: any) => boolean
  parameters: (data: any) => boolean
}

export type GetPetsOperationValidator = Validator

export type CreatePetOperationValidator = Validator

export type GetPetOperationValidator = Validator
