// THIS FILE IS GENERATED BY CODE GENERATOR. DO NOT CHANGE MANUALLY.
/* tslint:disable */
/* eslint-disable */

export function GetPetsValidator (data: any): boolean

export function CreatePetValidator (data: any): boolean

export function GetPetValidator (data: any): boolean
