// THIS FILE IS GENERATED BY CODE GENERATOR. DO NOT CHANGE MANUALLY.
/* tslint:disable */
/* eslint-disable */
declare namespace validators {
  
  declare function PetValidator (data: any): boolean
  
  declare function PetSeedValidator (data: any): boolean
  
}
