// THIS FILE IS GENERATED BY CODE GENERATOR. DO NOT CHANGE MANUALLY.
/* tslint:disable */
/* eslint-disable */

export function PetValidator (data: any): boolean

export function PetSeedValidator (data: any): boolean
